repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: android-lint
        name: android lint
        entry: ./gradlew lintDebug
        language: system
        pass_filenames: false
        files: \.(kt|xml|gradle)$
